// <auto-generated />
using System;
using Assignment.Entities.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assignment.Entities.Migrations
{
    [DbContext(typeof(FileUploadDbContext))]
    partial class FileUploadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assignment.Entities.DBModels.FileUploadInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("filepath");

                    b.Property<string>("FileType")
                        .HasColumnType("text")
                        .HasColumnName("filetype");

                    b.Property<string>("MakeBy")
                        .HasColumnType("text")
                        .HasColumnName("makeby");

                    b.Property<DateTime?>("MakeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("makedate");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("updateby");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedate");

                    b.HasKey("Id");

                    b.ToTable("fileUploadInfo", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
